export  const Routes={
    DASHBOARD:"DASHBOARD",
    PUBLIC:"PUBLIC",
    LOGIN:"LOGIN",
    SIGNUP:"REGISTER",
    FORGOT_PASSWORD:"FORGOT_PASSWORD",
    RESET_PASSWORD:"RESET_PASSWORD",
    ADD_USER_MODAL:"ADD_USER_MODAL",
    ADD_DETAILS_MODAL:"ADD_DETAILS_MODAL",
    USER_DETAILS:"USER_DETAILS",

}