export  const Routes={
    DASHBOARD:"DASHBOARD",
    PUBLIC:"PUBLIC",
    LOGIN:"LOGIN",
    SIGNUP:"REGISTER",
    FORGOT_PASSWORD:"FORGOT_PASSWORD",
    RESET_PASSWORD:"RESET_PASSWORD",
    ADD_MEMBER:"ADD_MEMBER",
    EDIT_USER:"EDIT_USER",
    ADD_DETAILS:"ADD_DETAILS",
    PRICE:"PRICE",
    USER_DETAILS:"USER_DETAILS",
}